# Generated by Django 3.1.4 on 2020-12-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplans',
            options={'verbose_name': 'День и план', 'verbose_name_plural': 'Дни и планы'},
        ),
    ]
