# Generated by Django 3.1.4 on 2021-01-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0004_themes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
