# Generated by Django 3.1.4 on 2021-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0010_auto_20210327_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.BooleanField(default=False, verbose_name='theme'),
        ),
    ]
