# Generated by Django 3.1.4 on 2021-03-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0015_auto_20210328_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.BooleanField(default=False, verbose_name='theme'),
        ),
    ]
