# Generated by Django 3.1.4 on 2021-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.BooleanField(),
        ),
    ]
