# Generated by Django 3.1.4 on 2021-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0007_auto_20210120_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='White', max_length=5),
        ),
    ]
