# Generated by Django 3.1.4 on 2021-03-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplan', '0013_auto_20210328_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
